### ISSUE TITLE
Support webpack integration

### ISSUE THREAD

**Issue by manthey** [Caleydo/lineup.js#109]
I'm using LineUp in another project which uses webpack for its packaging step.  Webpack doesn't work well including the dist/LineUpJS.js file, as the `require` function is not what it expects, but it does work just fine if I `import LineUpJS from 'LineUpJS/src/main.js';` (my project uses ES6 and Babel).  I think this would work just as well with `require('LineUpJS/src/main.js');`

It would be great if there were a distribution file for webpack, too.

**Comment by ronichoudhury** [comment]
Zombie thread time: when you said "distribution file for webpack", what did you mean exactly?

**Comment by ronichoudhury** [comment]
Zombie thread time: when you said "distribution file for webpack", what did you mean exactly?

**Comment by ronichoudhury** [comment]
Zombie thread time: when you said "distribution file for webpack", what did you mean exactly?

**Comment by sgratzl** [comment]
latest build system is based on webpack
