### ISSUE TITLE
Allow library users to render their own cell/row/column content

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup.js#115]
In many cases, library users want to render their own content inside the cells. An example is an enRoute application that wants to show mutation data within the cells or aggregated mini box plots.

There are two options to implement this:
1) Give library users the possibility to implement their own cell content renderer
2) Implement a series of cell content renderers that library users can fill with data (e.g., an embedded boxplots, sparklines, etc.)

**Comment by sgratzl** [comment]
the library is designed that custom models and renderers can be easily integrated. I will create a test repo adding a simple new renderer / model.

**Comment by sgratzl** [comment]
a simple project is located at https://github.com/sgratzl/lineup_custom_renderer
