### ISSUE TITLE
Support label for categorical column renderer

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineup.js#120]
At the moment the categories for a categorical column accept a string array. However, it might be useful to provide a different label for each category instead of the actual value. 

![lineup_category_label](https://cloud.githubusercontent.com/assets/5851088/17771670/972188e6-6544-11e6-95fa-787e0d2122ef.PNG)

**Comment by sgratzl** [comment]
to be precise: it can either be a string array = list of categories or a list of objects (name, color). You are suggesting adding an third optional `label` field

**Comment by thinkh** [comment]
Yes, that's what I mean. So far we worked around that problem, by adding a new categorical column with the labels as categories and mapping the value for all rows to that label.

```javascript
var col = categoricalCol('gender_cat', ['female', 'male'], 'Gender'),
//...
rows.forEach((r) => r.gender_cat = r.gender === 'f' ? 'female' : 'male');
```
