### ISSUE TITLE
Support different shapes for categorical values (instead of colors)

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineup.js#121]
The color mapping for categories might be confusing and contradicting with the same column color mapping.

A solution might be support different shapes for categories instead of colors.

![column_color_mapping](https://cloud.githubusercontent.com/assets/5851088/17771739/ff73695a-6544-11e6-8709-008d6fbd6b01.PNG)

**Comment by sgratzl** [comment]
see #115 and https://github.com/sgratzl/lineup_custom_renderer
