### ISSUE TITLE
Is it possible to load and save weights?

### ISSUE THREAD

**Issue by carowjp** [Caleydo/lineup.js#123]
Is it possible to load and save weights in addition to table data?

**Comment by mstreit** [comment]
You can save and load the weights by putting them in a JSON file (see https://github.com/Caleydo/lineup.js/blob/master/demo/data/data_small.json). However, this is not yet integrated in the demo.

**Comment by carowjp** [comment]
Marc, thanks for your reply. What is the best forum for discussion and general questions regarding Caleydo? Should I post to github, email..what is your preference?

**Comment by mstreit** [comment]
Github is fine. We collect all framework related question about Caleydo web in the caleydo_web_container repo (https://github.com/Caleydo/caleydo_web_container/issues).
