### ISSUE TITLE
Show cell values for selected rows

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup.js#126]
At the moment we only show the values on mouse over:
![image](https://cloud.githubusercontent.com/assets/4129755/18552343/4a60cfa2-7b5c-11e6-882c-b7e9175ba53d.png)

The only way to find out what the values of the selected rows are is to deselect it and hover over the row. This is tedious. I suggest to always show the values for mouse over and selected rows.

**Comment by sgratzl** [comment]
part of latest release_1 branch
