### ISSUE TITLE
Round decimal digits

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup.js#127]
Showing two decimal digits should be sufficient in most of the cases, right? 

![image](https://cloud.githubusercontent.com/assets/4129755/18552431/b3651094-7b5c-11e6-9622-b0c6b2809246.png)

Rounding decimal places could be problematic if the values are very low.

**Comment by sgratzl** [comment]
just a configuration issue. 

for a number column if the column description contains a `numberFormat` field it will be used to create a D3 formatter. 

default value `.3n`

**Comment by mstreit** [comment]
ok, then let's change the default for our demos to something shorter.
