### ISSUE TITLE
Integrate new GUI importer into demo page

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup.js#149]

**Comment by sgratzl** [comment]
you know that the importer is phovea based, right

**Comment by sgratzl** [comment]
see also #151

**Comment by mstreit** [comment]
right. is there a way to extract the essential to a separate LineUp importer? however, the issue is not critical at the moment. I just raised it because @pkerpedjiev was not able to load his data (as posted slack).

**Comment by sgratzl** [comment]
in #151 I suggest to extract the demo page anyhow. The whole demo page then could be a phovea app
