### ISSUE TITLE
Extract Demo Page to own repository

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineup.js#151]
the demo page (everything under `/demo`) is not part the library and should be extracted to avoid confusion what LineUp provides.

**Comment by sgratzl** [comment]
https://sgratzl.github.io/lineup_demos/

**Comment by sgratzl** [comment]
see also #159, #155, #157, #156, #155

**Comment by sgratzl** [comment]
Do we agree on doing that , because then 
 * all the mentioned issues should be moved 
 * the gh-page branch should go offline
 * the demo page itself should be removed from the repository

**Comment by mstreit** [comment]
yes, I think that's a good idea.

**Comment by sgratzl** [comment]
that raises another question: where to host the lineup_demos and its source code? I don't like the current approach, since it misuse git and Github gh-pages

**Comment by mstreit** [comment]
how about moving it to AWS? could also be part of demo.caleydo.org.

**Comment by sgratzl** [comment]
at the moment it is possible since it is a static website only. I can configure nginx to host it directly and not forward to the caleydo web installation. But it won't be listed under demo.caleydo.org since it is not a caleydo web application and there is no process for packaging phovea applications. see also https://github.com/orgs/phovea/projects/2
