### ISSUE TITLE
Can't load saved gist file

### ISSUE THREAD

**Issue by pkerpedjiev** [Caleydo/lineup.js#155]
We created a lineup view, saved it as a gist. Trying to load it again leads to an error.

Saved link:

http://www.caleydo.org/lineup.js/demo/#gist:836fe14223dc29d7d63837ceb3c49e25

Error:

    Uncaught SyntaxError: Unexpected number in JSON at position 921596(…)

![image](https://cloud.githubusercontent.com/assets/2143629/20063971/02db70de-a4d7-11e6-93b1-ec9f28d28186.png)

Location of the gist:

https://gist.github.com/anonymous/836fe14223dc29d7d63837ceb3c49e25

**Comment by ngehlenborg** [comment]
Here is the file we started out with:

[all_decade_genes.csv.zip](https://github.com/Caleydo/lineup.js/files/575806/all_decade_genes.csv.zip)

(needs to be extracted, only compressed to attach here)

**Comment by thinkh** [comment]
The content is probably longer than what you can store into a gist. It's for sure no valid JSON data:

![no-valid-json-content](https://cloud.githubusercontent.com/assets/5851088/20064203/2cca143a-a50a-11e6-9197-3a4f85f38d06.png)

How can I reproduce storing that gist?

**Comment by ngehlenborg** [comment]
We checked the gist and the last `_index` corresponds to the length of the original CSV file. It definitely stores the full structure in the gist ([836fe14223dc29d7d63837ceb3c49e25-8de8bab6b14e2323511b0fe34a3792b9148a1351.zip](https://github.com/Caleydo/lineup.js/files/575846/836fe14223dc29d7d63837ceb3c49e25-8de8bab6b14e2323511b0fe34a3792b9148a1351.zip)) but it seems to have issues retrieving it correctly.

<img width="477" alt="screen shot 2016-11-07 at 10 59 35 am" src="https://cloud.githubusercontent.com/assets/1216518/20064634/58f93116-a4d9-11e6-8153-ccf119947ee2.png">

**Comment by thinkh** [comment]
The `lineup.json` is sent correctly to the gist server, but as i described above has a certain limit.

![response-when-storing-gist](https://cloud.githubusercontent.com/assets/5851088/20064614/983f321c-a50b-11e6-8730-c273b38b855d.png)

**Comment by ngehlenborg** [comment]
Is the retrieval issue in LineUp? I can get the full gist out of Github without issues:

```bash
octothorpe:~ nils$ wget https://gist.githubusercontent.com/anonymous/836fe14223dc29d7d63837ceb3c49e25/raw/8de8bab6b14e2323511b0fe34a3792b9148a1351/lineup.json
--2016-11-07 11:05:09--  https://gist.githubusercontent.com/anonymous/836fe14223dc29d7d63837ceb3c49e25/raw/8de8bab6b14e2323511b0fe34a3792b9148a1351/lineup.json
Resolving gist.githubusercontent.com... 151.101.116.133
Connecting to gist.githubusercontent.com|151.101.116.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6981285 (6.7M) [text/plain]
Saving to: 'lineup.json'

lineup.json         100%[===================>]   6.66M  12.1MB/s    in 0.5s    

2016-11-07 11:05:10 (12.1 MB/s) - 'lineup.json' saved [6981285/6981285]

octothorpe:~ nils$ md5 lineup.json 
MD5 (lineup.json) = 78241327fd2b2fee316330bacd7a7f04
octothorpe:~ nils$ md5 Downloads/836fe14223dc29d7d63837ceb3c49e25-8de8bab6b14e2323511b0fe34a3792b9148a1351/lineup.json 
MD5 (Downloads/836fe14223dc29d7d63837ceb3c49e25-8de8bab6b14e2323511b0fe34a3792b9148a1351/lineup.json) = 78241327fd2b2fee316330bacd7a7f04
octothorpe:~ nils$ 
```

The MD5 checksums are identical whether I download via the website "ZIP" download or via the commandline using `wget`. I confirmed that the complete file is complete in both cases. Seems to be an issue either with how LineUp is downloading the file from GitHub or with LineUp itself.

**Comment by thinkh** [comment]
Interesting. The total length of the `lineup.json` content is 921600. 

![json-length](https://cloud.githubusercontent.com/assets/5851088/20066940/a51ce09e-a513-11e6-9e06-283e5d1e0a2f.PNG)

When I want to print that string the Chrome developer tools crash. I couldn't find any hint if the `JSON.parse` implementation or polyfill we use is limited to a certain string length. Maybe you can continue at that point.

**Comment by ngehlenborg** [comment]
Ok, here's what I found:

The `content` field in the `gistdesc` object does not contain the full file content, only up to the point where the Gist UI truncates the file (see note "This file has been truncated, but you can view the full file."):

Gist website:
![screen shot 2016-11-07 at 12 18 51 pm](https://cloud.githubusercontent.com/assets/1216518/20067740/64edbb26-a4e4-11e6-90a4-47419ae3b59b.png)

`content` of `gistdesc` for first file in Safari dev tools:
![screen shot 2016-11-07 at 12 19 25 pm](https://cloud.githubusercontent.com/assets/1216518/20067803/8a0015b2-a4e4-11e6-9fd4-90d8948f651f.png)

The correct way to load files from Gists seems to be to use the `raw_url` field and pull the file in using a second `d3.json` call, rather than relying on the `content` field:

https://jsfiddle.net/pzuw423j/6/

@thinkh: If you can add this today, I'd be very grateful.

**Comment by thinkh** [comment]
@ngehlenborg change is working. I deployed the demo by merging the master into the gh-pages branch.
