### ISSUE TITLE
"Export to CSV" feature leads to unexpected results

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/lineup.js#156]
**Replicate**:

  1. Load data into LineUp.js and configure visualization (see screenshot 1): [all_decade_genes.csv.zip](https://github.com/Caleydo/lineup.js/files/575834/all_decade_genes.csv.zip) (please extract)
  1. Click "export to csv".
  1. Save resulting blob to CSV file in Safari: [all_decade_combined.csv.zip](https://github.com/Caleydo/lineup.js/files/575835/all_decade_combined.csv.zip) (please extract)
  1. Load saved CSV back into LineUp.js (see screenshot 2)

_Screenshot 1_
![screen shot 2016-11-07 at 10 47 06 am](https://cloud.githubusercontent.com/assets/1216518/20064313/4359cc0e-a4d8-11e6-9dd4-05be905258b8.png)

_Screenshot 2_
![screen shot 2016-11-07 at 10 47 34 am](https://cloud.githubusercontent.com/assets/1216518/20064330/4fdeaf58-a4d8-11e6-93f8-324e362595a6.png)

**Observed**:

Screenshot 2

**Expected**:

Screenshot 1

Is this what I am expected to see?

**Comment by sgratzl** [comment]
Is it an import or export problem? Does the exported CSV itself makes sense?

**Comment by mstreit** [comment]
I assume that the export works fine but that the old black box importer makes the wrong assumptions.
@ngehlenborg, please try with the import dialog that is used in the new demo:
https://sgratzl.github.io/lineup_demos/

**Comment by ngehlenborg** [comment]
I tried with the new demo and I now I see what the problem is. A combined column results in a new column in the CSV and each column within the combined column gets written as well. 

I would be helpful to have more information about what the export function does (unlike the gist feature, it does not create a file that allows me to reproduce a previous view). We should provide an option to save the stuff that gets written to a gist to local disk as well and reload from there.

**Comment by sgratzl** [comment]
so you want a "download json" feature -> https://github.com/sgratzl/lineup_demos
