### ISSUE TITLE
Infer data types from available data

### ISSUE THREAD

**Issue by pkerpedjiev** [Caleydo/lineup.js#159]
Lineup should infer the underlying data type (e.g. 'categorical', 'numerical') from the data that is present. If there is missing data (e.g. blank fields), it should not immediately imply that data is categorical. The data type should be inferred from the values that are present.

If all other fields are numerical, blank fields should either be ignored (if possible) or assumed to be zero.

**Comment by pkerpedjiev** [comment]
Here's an [example file](https://drive.google.com/file/d/0B2amcfXKOyc3QjRrQU4xREN6R1E/view?usp=sharing).

If I select `Integer` values in the data type chooser, bars are not displayed for any years except the last one. Using mouseover also shows floating point values.

![image](https://cloud.githubusercontent.com/assets/2143629/20185991/3e87b676-a73c-11e6-927a-9c5035f10373.png)

**Comment by sgratzl** [comment]
see also https://github.com/phovea/phovea_importer/issues/51

**Comment by sgratzl** [comment]
btw. @pkerpedjiev if you are sick of the loading issues, why not creating an own phovea app similar to lineup_demos?

**Comment by pkerpedjiev** [comment]
I'm not sick of loading issues. This was just a suggestion (and an 
actual bug report in the comment). If you don't think it's a valid 
suggestion, that's fine, but I think it's a little odd to suggest that I 
replicate lineup_demos just to load one dataset.

In the end, I loaded it in Numbers and shared some screenshots from 
there with collaborators. We wanted to give them a link to LineUp.js, 
but without this functionality it makes no sense to do so.

The question I would pose to you is whether you want this to be an 
actual usable application or just a demo? If it's the latter, that's 
fine. Keep this issue closed and I'll use other applications for my data.

**Comment by sgratzl** [comment]
> If you don't think it's a valid suggestion

I moved the issue to the corresponding respository, in this case the phovea_importer, if you take a close look ad the references of this ticket

It was a suggestion to build a simple own example, because if you take a look at the code how the integrated demos are loaded. Adapting the code is faster and simpler than dealing with importing issues.

**Comment by pkerpedjiev** [comment]
Alright, thanks.
