### ISSUE TITLE
columns should allow the user to switch renderers

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineup.js#163]
e.g., the renderer of a multi-value numerical column should be switchable from a heatmap to a box plot.

**Comment by thinkh** [comment]
Merged PR https://github.com/Caleydo/lineup.js/pull/170.

@mstreit Please close issue, if done from your side.

**Comment by sgratzl** [comment]
the class `Column` now has a method `rendererType` that returns the type of the renderer to use. 

default: 
```
rendererType(): string {
   return this.desc.type;
}
```

@bikramkawan could also be interested for your case

**Comment by mstreit** [comment]
Where or how can I test this?

**Comment by mstreit** [comment]
@thinkh told me that there is no UI to switch the renderers. @bikramkawan, you plan to work on this, right?

**Comment by mstreit** [comment]
@bikramkawan, you finished this already, right? Please keep the tickets up to date so that everyone knows what's going on.

**Comment by bikramkawan** [comment]
Here is the first iteration .
![image](https://cloud.githubusercontent.com/assets/12292333/20747668/3fc93dc0-b6eb-11e6-9695-30c13ff0318b.png)

**Comment by mstreit** [comment]
OK. Please change "Renderer Type" to something a user can understand, like "Visualization".
Same for the visualization techniques, e.g., heatmapcustom needs to be replaced with a proper label.

**Comment by mstreit** [comment]
Only close issues if the new feature, enhancement or bugfix was merged into the master.

**Comment by bikramkawan** [comment]
Here is the update after correcting label and renderer. 
![dec-07-2016 9-42-02 pm](https://cloud.githubusercontent.com/assets/12292333/20985764/23d7931a-bcc6-11e6-9c29-eb93617dfda7.gif)

Thanks @thinkh for help :)
