### ISSUE TITLE
histograms do not work

### ISSUE THREAD

**Issue by andreassteffen** [Caleydo/lineup.js#58]
when clicking on the histogram check box, nothing happens in the browser (chrome).
console error message:
Uncaught TypeError: Cannot read property 'map' of undefined --> d3.js:6667

**Comment by sgratzl** [comment]
are you using some special dataset, since the default one http://caleydo.github.io/lineup.js/demo/# seem to work

**Comment by sgratzl** [comment]
fix in 7cf6353748105c85d1b0eab654afb968af2e6728
