### ISSUE TITLE
save layout

### ISSUE THREAD

**Issue by andreassteffen** [Caleydo/lineup.js#59]
save layout button saves layout plus data.

**Comment by sgratzl** [comment]
saving is just part of the demo application and should save the config as well as the data aka "save project".

however, the relevant code is:
```js
var descs = lineup.storage.getColumnLayout()
      .map(function (d) {
        return d.description();
      });
var layout = _.groupBy(descs, function (d) {
      return d.columnBundle;
    });
```
the variable `layout` contains the description of the layout and can be used as a parameter while setting up the datastore.
