### ISSUE TITLE
How did you include opening and saving files?

### ISSUE THREAD

**Issue by Christian4561** [Caleydo/lineup.js#63]
I'm building a web app and I keep hearing that the browser doesn't have access to the file system. How did you do it?

**Comment by sgratzl** [comment]
You can't select files by your own, the user has to choose a file or drag it into your website. After that you can use the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API to access and read the file

**Comment by Christian4561** [comment]
But how did you get the choose file button and the ability to save files?

**Comment by sgratzl** [comment]
take a look at this tutorial: http://www.html5rocks.com/en/tutorials/file/dndfiles/ it explains how to load a file in JavaScript. 

For writing a file we use [FileSaver.js](https://github.com/eligrey/FileSaver.js/) library
