### ISSUE TITLE
Redesign Tooltip

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineup.js#67]
Here is the current state of the LineUp tool-tip. 

![image](https://cloud.githubusercontent.com/assets/2039375/8800038/87f25556-2faf-11e5-8e62-a6e6f4117fee.png)

1. we shouldn't show the original and the derived values, we should decide on one instead, and I think it should be the original values.
2. the table is hideous. I don't think we need it at all.

**Comment by sgratzl** [comment]
> the table is hideous. I don't think we need it at all.

disable via `interaction.tooltips=false` in the config options

**Comment by alexsb** [comment]
The derived values are shown in the original lineup, but they use the unit interval. Was there a reason to not use the unit interval but an interval of 1..100?

**Comment by mstreit** [comment]
Agreed. I will turn the tooltip off by default.
I also think that we should stick to the unit interval, which we also used in the original version.

**Comment by sgratzl** [comment]
tooltips were removed during the TypeScript rewrite
