### ISSUE TITLE
Upload File Redesign

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineup.js#72]
The "upload file" text uses a style that is used for clickable widgets elsewhere, but it isn't clickable. I'd suggest to just show that in black, no icon, as "Upload file:"

Alternatively we could just remove the whole "upload" and "choose file" and "no file chose" and just change  the drop target to "To upload data drop file here or click to select file."  This is a common approach nowadays. Two different event listeners, one for drop action one for click action.

**Comment by mstreit** [comment]
The second alternative sounds good.
