### ISSUE TITLE
link column

### ISSUE THREAD

**Issue by andreassteffen** [Caleydo/lineup.js#84]
hi,
is it possible to add a link column without filter and sorting functionality? I remember it was possible in the targid version.
Many thanks, Andreas

**Comment by sgratzl** [comment]
what do you mean by link column?

there is a possibility to add an "action" column, e.g. like the "detail button" in targid. In the newer version, there is also a link column that allows you to use one value and create a link out of it, e.g. https://duckduckgo.com/?q=<genename>

btw. https://github.com/sgratzl/lineup.js is the most recent version

**Comment by andreassteffen** [comment]
yes, the detail is what I meant. Many thanks!

**Comment by andreassteffen** [comment]
is there somewhere an example of how I use of the action and the link column? 
would be very helpful. many thanks!

**Comment by andreassteffen** [comment]
ok, understood if from the code, which is really cool! thanks.
