### ISSUE TITLE
Add checkbox column to enable multi-selection

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineup.js#92]
# Current status
Multi-selections are only possible on Windows, because the control key + click triggers the right click menu on a Mac. 

# Suggestion
Add a checkbox column to the most left, if multi-selection is enabled in LineUp (so not by default). When activating a checkbox a selection event should be triggered.

This would make it easy for every OS and device (also touch) to select multiple rows.

**Comment by sgratzl** [comment]
I created a new column type: 'selection', see e.g. https://github.com/Caleydo/lineup.js/blob/master/demo/test.js#L45 how to apply it

**Comment by thinkh** [comment]
Thanks for the fast implementation. I will give it a try.
