### ISSUE TITLE
`RemoteDataProvider` example

### ISSUE THREAD

**Issue by bkj** [Caleydo/lineup.js#99]
Does anyone know of an example using the `RemoteDataProvider` class?

I'm interested in running Lineup on a fairly large dataset (10s of thousands of records) and was wondering about the feasibility of implementing a server backend.  It looks like there is already some code that shows what that API might look like, but an example would be very useful.

Thanks

**Comment by sgratzl** [comment]
hi, take a look at https://github.com/sgratzl/lineup_remote
